remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

title: Why are extremophiles so extreme?
description: Senior Research Project - Fall 2023

# Extremophiles
Senior Research Project from Fall 2023

## Why are extremophiles so extreme?
A comparative genomic analysis of horizontal gene transfer in Deinococcus radiodurans

## Abstract
This research project aims to confirm horizontal gene transfer in the extremophilic bacterium Deinococcus radiodurans, revealing the genetic adaptations responsible for its exceptional resilience in hostile environments. Employing advanced bioinformatics tools, including BLAST and GALAXY, a comparative genomic analysis will be conducted focusing on genes crucial for stress response and radiation resistance in D. radiodurans, examining their sequence similarities with its closest relative, Thermus thermophilus, and potentially other organisms. The study's significance lies in verifying the genetic mechanisms underpinning D. radiodurans' adaptability, with potential applications in biotechnology and medicine. Prior studies have explored extremophile genetics and inspired this project, particularly Omelchenko et al., who identified horizontal gene transfer in T. thermophilus and D. radiodurans. Expected outcomes include confirming horizontal gene transfer and producing tangible products like an oral presentation, a research manuscript, and well-organized code, contributing to the understanding of extremophile genetics and horizontal gene transfer's broader implications.
